---
book_repo: pivotal-cf/docs-book-release-notes
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/pcf-release-notes
    ref: '2.0'
  directory: pivotalcf/2-0/pcf-release-notes
  subnav_template: rn_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 2.0
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Release Notes
    search_placeholder: Search PCF Release Notes
    url_prefix: pivotalcf/2-0/pcf-release-notes
    local_product_version: 2.0
    local_header_links: []
    local_header_version_list:
